# -*- coding: utf-8 -*-
# id, ko, sci, emoji, group, evidence, count, countSrc, exact(개체수 측정 여부), blurb, facts[]
CREATURES = [
 dict(id="human", ko="인간", sci="Homo sapiens", emoji="🧑", group="영장류",
   evidence="msr-pass", count=8_160_000_000, measured=True,
   countSrc="UN World Population Prospects 2024 · 2026년 중위추계 195개국 합계",
   blurb="생후 18~24개월이면 거울 속 얼굴이 자기라는 걸 알아차린다. 지구상에서 유일하게 자기 자신에 대한 이야기를 글로 남기고, 그 이야기를 자기 자신이 다시 읽는 종이다.",
   facts=["🧠 뇌 약 1,350 g · 대뇌 뉴런 약 860억 개",
          "🪞 갤럽(1970) 이후 모든 거울 실험의 기준선",
          "🌍 인간이 뽑히면 어느 나라에서 태어날지 한 번 더 추첨한다"]),

 dict(id="chimpanzee", ko="침팬지", sci="Pan troglodytes", emoji="🐒", group="영장류",
   evidence="msr-pass", count=200_000, measured=True,
   countSrc="IUCN Red List (야생 17만~30만, 멸종위기)",
   blurb="1970년 갤럽의 첫 거울 실험을 통과한 인간 외 최초의 동물. 마취 중에 몰래 찍어둔 이마의 점을 거울을 보며 손으로 만진다. 도구를 만들고, 무리마다 다른 문화를 가지며, 30년 넘게 서로를 기억한다.",
   facts=["🧠 뇌 약 400 g · 인간과 DNA 약 98.8% 공유",
          "🪞 거울 자기인식 통과 (Gallup 1970)",
          "⚠️ 야생 개체는 계속 감소 중"]),

 dict(id="bonobo", ko="보노보", sci="Pan paniscus", emoji="🦧", group="영장류",
   evidence="msr-pass", count=17_500, measured=True,
   countSrc="IUCN Red List (야생 1.5만~2만, 멸종위기)",
   blurb="콩고강 남쪽에만 사는, 침팬지와 가장 가까운 사촌. 싸움보다 화해를 택하는 사회를 만들고 암컷이 무리의 중심에 선다. 거울 속 자신을 알아보고, 사람의 말소리에 담긴 뜻까지 배운다.",
   facts=["🧠 뇌 약 350 g · 공감·화해 행동이 두드러짐",
          "🪞 거울 자기인식 통과",
          "⚠️ 서식지가 콩고민주공화국 한 곳뿐"]),

 dict(id="orangutan_borneo", ko="보르네오오랑우탄", sci="Pongo pygmaeus", emoji="🦧", group="영장류",
   evidence="msr-pass", count=104_700, measured=True,
   countSrc="IUCN Red List 2016 재평가 (약 10만 4,700, 멸종위기)",
   blurb="나무 위에서 거의 혼자 사는 대형 유인원. 매일 밤 잎으로 새 잠자리를 엮고, 비가 오면 잎을 우산처럼 쓴다. 거울을 주면 입을 벌려 이빨과 혀를 살펴본다.",
   facts=["🧠 뇌 약 370 g · 도구 사용과 문화 전승 확인",
          "🪞 거울 자기인식 통과",
          "⚠️ 1999년 이후 보르네오에서 약 10만 마리 감소"]),

 dict(id="orangutan_sumatra", ko="수마트라오랑우탄", sci="Pongo abelii", emoji="🦧", group="영장류",
   evidence="msr-pass", count=13_850, measured=True,
   countSrc="IUCN Red List (약 1만 3,800, 심각한 위기)",
   blurb="수마트라 북부의 열대우림에만 남은 오랑우탄. 보르네오 사촌보다 더 사회적이고, 나뭇가지로 벌레를 낚는 도구를 만든다. 남은 개체가 인간 한 도시의 주민 수보다 적다.",
   facts=["🧠 도구 제작·모방 학습이 특히 발달",
          "🪞 거울 자기인식 통과",
          "⚠️ 심각한 위기(CR) · 서식지가 한 섬의 북단뿐"]),

 dict(id="dolphin", ko="큰돌고래", sci="Tursiops truncatus", emoji="🐬", group="고래류",
   evidence="msr-pass", count=750_000, measured=True,
   countSrc="IUCN Red List (최소 75만, 개체수 안정)",
   blurb="손이 없어 마크를 만질 수 없으니, 거울 앞에서 몸을 비틀어 표시된 부위를 비춰 본다. 사람보다 이른 생후 7개월에 자기인식이 나타나고, 서로를 부르는 고유한 휘슬 이름을 가진다.",
   facts=["🧠 뇌 약 1,600 g · 체중 대비 뇌 크기가 인간에 근접",
          "🪞 거울 자기인식 통과 (Reiss & Marino 2001)",
          "🔊 개체마다 고유한 '시그니처 휘슬' = 이름"]),

 dict(id="orca", ko="범고래", sci="Orcinus orca", emoji="🐋", group="고래류",
   evidence="msr-pass", count=50_000, measured=True,
   countSrc="IUCN 자료부족(DD) · 통용 추정치 약 5만",
   blurb="무리마다 사냥법과 방언이 다르고, 그것을 세대에 걸쳐 물려준다. 할머니 범고래가 무리를 이끌고, 폐경 이후에도 수십 년을 살며 지식을 전한다. 거울 속 자신을 알아본다는 보고가 있다.",
   facts=["🧠 뇌 약 5,600 g · 동물 중 두 번째로 큼",
          "🪞 자기인식 보고 있음 (Delfour & Marten 2001)",
          "👵 인간·범고래·들쇠고래만 폐경 후 오래 산다"]),

 dict(id="horse", ko="말", sci="Equus ferus caballus", emoji="🐎", group="포유류",
   evidence="msr-pass", count=56_211_907, measured=True,
   countSrc="FAOSTAT 2024 사육두수 5,621만 1,907",
   blurb="2021년 실험에서 14마리 중 11마리가 거울을 보고 뺨에 칠해둔 색 표시를 지우려 했다. 사람의 표정을 구분해 기억하고, 몇 달 뒤 다시 만난 사람이 전에 자기에게 화를 냈는지도 알아본다.",
   facts=["🧠 뇌 약 620 g · 사람 얼굴·목소리 장기 기억",
          "🪞 거울 자기인식 통과 (Baragli et al. 2021)",
          "🐴 가축 5,621만 마리 + 야생화 개체"]),

 dict(id="mouse", ko="생쥐", sci="Mus musculus", emoji="🐁", group="포유류",
   evidence="msr-pass", count=10_000_000_000, measured=False,
   countSrc="자릿수 추정 10¹⁰ · Bar-On et al. PNAS 2018 SI Table S1의 포유류 자릿수 범위에서",
   blurb="2023년 실험에서 생쥐가 거울을 보고 머리에 묻은 흰 표시를 지우려 하는 것이 확인됐다. 단, 익숙한 상대와 함께 자란 개체에서만 나타났다 — 자기를 알려면 남을 먼저 알아야 했던 셈이다.",
   facts=["🧠 뇌 약 0.4 g · 해마 신경세포 신생이 활발",
          "🪞 거울 자기인식 통과 (Yokose et al. 2023, 사회 경험 필요)",
          "📊 전 세계 개체수는 자릿수 추정치"]),

 dict(id="cleaner_wrasse", ko="청줄청소놀래기", sci="Labroides dimidiatus", emoji="🐟", group="어류",
   evidence="msr-pass", count=100_000_000, measured=False,
   countSrc="자릿수 추정 10⁸ · 전 세계 개체수 추정치 미출판",
   blurb="어류가 거울 테스트를 통과한다는 사실은 2019년에 처음 보고됐고 2022년 후속 연구로 신뢰가 높아졌다. 목에 기생충처럼 갈색 표시를 해두면, 거울을 확인한 뒤 바닥에 목을 긁어 지우려 한다.",
   facts=["🧠 뇌 무게 1 g 미만 · 큰 물고기 100마리 이상의 얼굴을 기억",
          "🪞 거울 자기인식 통과 (Kohda et al. 2019 · 2022)",
          "🧼 다른 물고기 몸의 기생충을 떼어먹는 '청소부'"]),

 dict(id="ghost_crab", ko="대서양유령게", sci="Ocypode quadrata", emoji="🦀", group="갑각류",
   evidence="msr-pass", count=1_000_000_000, measured=False,
   countSrc="자릿수 추정 10⁹ · 전 세계 개체수 추정치 미출판",
   blurb="거울 앞에서 같은 종의 다른 게에게 하는 위협 행동을 하지 않는다 — 반사된 상대가 '남'이 아님을 구분한다는 뜻이다. 연구자들은 이를 원시적 형태의 자기 인식으로 해석했다.",
   facts=["🧠 뇌가 아니라 신경절 다발로 판단한다",
          "🪞 원시적 자기인식 보고 (Carvalho et al. 2023)",
          "🏖️ 대서양 모래 해변의 구멍 속에서 산다"]),

 dict(id="myrmica", ko="뿔개미(Myrmica 3종)", sci="Myrmica rubra 등", emoji="🐜", group="곤충",
   evidence="msr-pass", count=10_000_000_000_000, measured=False,
   countSrc="자릿수 추정 10¹³ · 전 세계 개미 2×10¹⁶(Schultheiss et al. PNAS 2022) 중 홀아크틱 온대 Myrmica 속의 비중으로 역산",
   blurb="개미가 거울 테스트를 통과했다는 보고는 논쟁적이지만 기록으로 남아 있다. Myrmica sabuleti·rubra·ruginodis 세 종은 이마에 파란 점을 찍어두면 거울을 본 뒤 더듬이와 앞다리로 그 부위를 문질러 지우려 했다.",
   facts=["🧠 뉴런 약 25만 개 · 그걸로 사회를 운영한다",
          "🪞 거울 자기인식 통과 보고 (Cammaerts & Cammaerts 2015, 논쟁 있음)",
          "📊 이 후보군에서 개체수가 가장 많다"]),

 dict(id="gorilla_west", ko="서부고릴라", sci="Gorilla gorilla", emoji="🦍", group="영장류",
   evidence="msr-debate", count=316_000, measured=True,
   countSrc="IUCN Red List (약 31만 6,000, 심각한 위기)",
   blurb="표준 거울 테스트에서는 대개 실패하는데, 마취를 쓰지 않고 거울에 충분히 익숙해진 개체는 통과한다. 수어를 배운 고릴라 코코가 대표적이다. 고릴라에게 눈을 오래 마주치는 건 위협이라, 거울을 오래 볼 이유가 없었을 뿐일 수도 있다.",
   facts=["🧠 뇌 약 500 g · 수어 학습 사례 있음",
          "🪞 조건에 따라 통과 (결과 논쟁 중)",
          "⚠️ 심각한 위기(CR) · 에볼라와 밀렵이 주요 위협"]),

 dict(id="gorilla_east", ko="동부고릴라", sci="Gorilla beringei", emoji="🦍", group="영장류",
   evidence="msr-debate", count=5_000, measured=True,
   countSrc="IUCN Red List (약 5,000, 심각한 위기 · 산악고릴라 약 1,060 포함)",
   blurb="르완다·우간다·콩고 국경의 산과 저지대 숲에만 남았다. 산악고릴라는 한때 300마리 아래로 줄었다가 보전 노력으로 1,000마리를 넘겼다 — 대형 유인원 중 개체수가 늘고 있는 유일한 사례다.",
   facts=["🧠 서부고릴라와 같은 수준의 인지 능력",
          "🪞 조건에 따라 통과 (결과 논쟁 중)",
          "📈 산악고릴라만은 개체수가 증가 중"]),

 dict(id="elephant_asian", ko="아시아코끼리", sci="Elephas maximus", emoji="🐘", group="포유류",
   evidence="msr-debate", count=45_000, measured=True,
   countSrc="IUCN Red List (야생 4만~5만, 멸종위기)",
   blurb="2006년 실험에서 세 마리 중 한 마리(해피)가 거울을 보며 이마의 X 표시를 코로 반복해 만졌다. 죽은 동료의 뼈에 멈춰 서고, 수십 년 전 만난 개체를 기억한다.",
   facts=["🧠 뇌 약 4,800 g · 소뇌 뉴런은 인간의 3배",
          "🪞 3마리 중 1마리 통과 (Plotnik et al. 2006)",
          "⚠️ 남은 야생 개체가 4만~5만 마리"]),

 dict(id="magpie", ko="유라시아까치", sci="Pica pica", emoji="🐦", group="조류",
   evidence="msr-debate", count=33_377_656, measured=True,
   countSrc="Callaghan et al. PNAS 2021 (추정 3,337만 · 95% CI 40만~26억)",
   blurb="포유류가 아닌 동물로 거울 테스트를 처음 통과한 종. 목의 노란 스티커를 거울로 확인하고 발로 긁어냈다. 다만 2020년 재현 연구가 실패해 결과는 논쟁 중이다. 사람 얼굴을 구분해 기억하고 원한도 오래 품는다.",
   facts=["🧠 뇌/체중비가 대형 유인원 수준",
          "🪞 통과 보고 (Prior et al. 2008) · 2020년 재현 실패",
          "🇰🇷 한국에서 가장 흔한 '자기인식 후보' 새"]),

 dict(id="house_crow", ko="집까마귀", sci="Corvus splendens", emoji="🐦‍⬛", group="조류",
   evidence="msr-debate", count=41_061_217, measured=True,
   countSrc="Callaghan et al. PNAS 2021 (추정 4,106만 · 95% CI 51만~34억)",
   blurb="남아시아 도시에 사람과 함께 사는 까마귀. 거울을 보고 표시된 부위를 향하는 행동이 관찰됐지만 재현 결과는 확실하지 않다. 도시의 신호등과 자동차 흐름을 학습해 이용한다.",
   facts=["🧠 까마귀류 전반이 도구 사용·계획 능력 보유",
          "🪞 마크 지향 행동 관찰 (재현 불확실)",
          "🏙️ 사람 도시에 완전히 적응한 조류"]),

 dict(id="pigeon", ko="집비둘기", sci="Columba livia", emoji="🕊️", group="조류",
   evidence="msr-debate", count=285_765_338, measured=True,
   countSrc="Callaghan et al. PNAS 2021 야생 개체 추정 2억 8,577만 (95% CI 1.2억~6.6억) · 도시 야생화 개체는 별도",
   blurb="비둘기는 훈련을 충분히 받으면 거울 테스트를 통과한다 — 스키너 계열 실험에서 단계별로 학습시켰을 때다. '자발적으로 아는 것'과 '배워서 아는 것'의 경계에 서 있는 사례다.",
   facts=["🧠 사람 얼굴·미술 화풍·유방암 조직 사진까지 분류 학습 가능",
          "🪞 광범위한 훈련 후 통과 (Epstein et al. 1981)",
          "🏙️ 도시 야생화 개체를 합치면 실제 수는 훨씬 많다"]),

 dict(id="manta", ko="대왕쥐가오리", sci="Mobula birostris", emoji="🐠", group="어류",
   evidence="msr-partial", count=100_000, measured=False,
   countSrc="자릿수 추정 10⁵ · IUCN 멸종위기(EN), 전 세계 총계 미출판",
   blurb="거울 앞에서 반복적으로 몸을 뒤집고 지느러미를 흔들며 거품을 뿜었다. 같은 종을 만났을 때 하는 사회적 행동은 전혀 하지 않았다. 다만 결정적인 마크 테스트는 아직 이뤄지지 않았다.",
   facts=["🧠 어류 중 뇌/체중비가 가장 큰 부류",
          "🪞 자기지향 행동 관찰 (Ari & D'Agostino 2016) · 마크 테스트 미실시",
          "⚠️ 멸종위기(EN) · 아가미판 거래가 주요 위협"]),

 dict(id="pig", ko="집돼지", sci="Sus domesticus", emoji="🐷", group="포유류",
   evidence="msr-partial", count=962_441_623, measured=True,
   countSrc="FAOSTAT 2024 사육두수 9억 6,244만 1,623",
   blurb="거울에 비친 자기 모습을 향해 달려가는 대신, 거울에 보이는 먹이가 실제로 어디 있는지 몸을 돌려 찾아낸다 — '거울이 무엇인지'를 이해한다는 뜻이다. 다만 마크 테스트는 통과하지 못했다.",
   facts=["🧠 3세 아동 수준의 과제 학습·조이스틱 게임 수행",
          "🪞 거울 정보 활용은 하지만 마크 테스트는 미통과",
          "🔢 매년 약 15억 마리가 도축된다"]),

 dict(id="dog", ko="개", sci="Canis familiaris", emoji="🐕", group="포유류",
   evidence="msr-partial", count=900_000_000, measured=False,
   countSrc="추정 약 9억 (전 세계 반려·유기견 추정치, 출처별 8억~10억)",
   blurb="시각 거울 테스트는 실패하지만, 냄새로 하는 자기인식 테스트(STSR)는 통과한다. 자기 오줌 냄새는 대충 지나치고, 거기에 다른 냄새를 섞어두면 한참 킁킁거린다. '자기'를 코로 아는 동물이다.",
   facts=["🧠 후각 수용체 약 3억 개 (인간의 50배)",
          "👃 후각 자기인식(STSR) 통과 (Horowitz 2017)",
          "🪞 시각 거울 테스트는 실패"]),

 dict(id="chicken", ko="닭", sci="Gallus gallus domesticus", emoji="🐔", group="조류",
   evidence="ny", count=27_680_730_000, measured=True,
   countSrc="FAOSTAT 2024 사육 마리수 276억 8,073만",
   blurb="지구상 척추동물 중 개체수 1위. 자기 새끼가 곤란해지면 스스로 스트레스 반응을 보이고, 지금 먹을 작은 먹이와 조금 기다린 뒤의 큰 먹이 중에서 후자를 고를 수 있다. 뉴욕 선언은 조류의 의식을 '강력하게 지지되는 것'으로 분류한다.",
   facts=["🧠 자기 통제·공감 유사 반응·기초 산수 능력 보고",
          "🧠 조류는 뉴욕 선언(2024)에서 의식 근거가 강한 집단",
          "🔢 276억 마리 · 매년 약 750억 마리가 도축된다"]),

 dict(id="cattle", ko="소", sci="Bos taurus", emoji="🐮", group="포유류",
   evidence="ny", count=1_578_614_149, measured=True,
   countSrc="FAOSTAT 2024 사육두수 15억 7,861만 4,149",
   blurb="새로운 것을 배워 문제를 풀면 심장박동이 빨라지고 더 활발하게 움직인다 — 배움 자체를 기뻐한다는 뜻이다. 무리 안에 친한 상대가 정해져 있고, 그 상대와 떨어지면 스트레스 호르몬이 오른다.",
   facts=["🧠 학습 성공 시 긍정 정서 반응 측정됨",
          "🧠 포유류는 뉴욕 선언(2024)에서 의식 근거가 강한 집단",
          "🔢 15억 7,861만 마리"]),

 dict(id="elephant_african", ko="아프리카사바나코끼리", sci="Loxodonta africana", emoji="🐘", group="포유류",
   evidence="ny", count=415_000, measured=True,
   countSrc="IUCN Red List · Great Elephant Census 계열 추정 41만 5,000~50만 (멸종위기 EN)",
   blurb="거울 테스트는 아시아코끼리에서만 확인됐지만, 아프리카코끼리도 서로를 이름처럼 부르는 저주파 소리를 쓴다는 연구가 2024년에 나왔다. 죽은 동료 앞에서 멈춰 서고, 수십 년 전 지나간 물길을 기억한다.",
   facts=["🧠 뇌 약 5,000 g · 육상동물 중 최대",
          "🗣️ 개체별 호칭(이름) 사용 근거 (Pardo et al. 2024)",
          "⚠️ 멸종위기(EN) · 100년 전의 3% 수준"]),

 dict(id="grey_parrot", ko="회색앵무", sci="Psittacus erithacus", emoji="🦜", group="조류",
   evidence="ny", count=6_587_487, measured=True,
   countSrc="Callaghan et al. PNAS 2021 (추정 659만 · 95% CI 6.9만~5.8억)",
   blurb="알렉스라는 회색앵무는 100개가 넘는 단어를 뜻과 함께 쓰고, '없음(none)'이라는 개념을 스스로 말로 만들어냈다. 거울 마크 테스트는 통과하지 못했지만 거울로 숨은 물체를 찾아낸다.",
   facts=["🧠 색·모양·개수 개념을 언어로 조작 (Pepperberg)",
          "🪞 거울 마크 테스트는 실패, 거울 정보 활용은 가능",
          "⚠️ 멸종위기(EN) · 애완 거래가 주요 위협"]),

 dict(id="nc_crow", ko="뉴칼레도니아까마귀", sci="Corvus moneduloides", emoji="🐦‍⬛", group="조류",
   evidence="ny", count=221_690, measured=True,
   countSrc="Callaghan et al. PNAS 2021 (추정 22만 1,690 · 95% CI 2,514~1,982만)",
   blurb="갈고리 달린 도구를 직접 만들고, 여러 도구를 순서대로 써야 풀리는 문제를 처음 보고도 풀어낸다. 도구를 만드는 방식이 섬의 지역마다 다르고 그것이 대물림된다.",
   facts=["🧠 뉴런 밀도가 영장류를 능가 · 3단 도구 연쇄 사용",
          "🪞 거울 마크 테스트는 실패",
          "🏝️ 뉴칼레도니아 한 섬에만 산다"]),

 dict(id="raven", ko="큰까마귀", sci="Corvus corax", emoji="🐦‍⬛", group="조류",
   evidence="ny", count=47_152_451, measured=True,
   countSrc="Callaghan et al. PNAS 2021 (추정 4,715만 · 95% CI 1,237만~1.78억)",
   blurb="누가 자기 먹이를 훔쳐가는지 기억하고 몇 년 뒤에도 그 개체를 차별한다. 다른 까마귀가 자기를 보고 있을 가능성만으로도 먹이를 숨기는 행동을 바꾼다 — 남의 시선을 상상한다는 뜻이다.",
   facts=["🧠 미래 대비 저장·타자 관점 추론 (Bugnyar et al. 2016)",
          "🧠 조류는 뉴욕 선언(2024)에서 의식 근거가 강한 집단",
          "🌍 북반구 전역에 분포"]),

 dict(id="octopus", ko="참문어", sci="Octopus vulgaris", emoji="🐙", group="두족류",
   evidence="ny", count=1_000_000_000, measured=False,
   countSrc="자릿수 추정 10⁹ · 전 세계 개체수 추정치 미출판",
   blurb="뉴런의 3분의 2가 뇌가 아니라 여덟 개의 팔에 흩어져 있다. 팔 하나하나가 스스로 판단한다. 거울 테스트는 통과하지 못했지만, 영국은 2022년 법으로 두족류를 '감각 있는 존재'로 인정했다.",
   facts=["🧠 뉴런 약 5억 개 · 그중 3분의 2가 팔에 분포",
          "🧠 두족류는 뉴욕 선언(2024)의 의식 가능성 집단",
          "🇬🇧 영국 동물복지(감각)법 2022에서 감각 있는 존재로 인정"]),

 dict(id="cuttlefish", ko="참갑오징어", sci="Sepia officinalis", emoji="🦑", group="두족류",
   evidence="ny", count=1_000_000_000, measured=False,
   countSrc="자릿수 추정 10⁹ · 전 세계 개체수 추정치 미출판",
   blurb="색맹인데도 피부로 주변 색을 흉내내고, 몸 왼쪽과 오른쪽에 서로 다른 신호를 동시에 띄워 암컷에게는 구애를, 경쟁자에게는 위장을 보낸다. 좋아하는 먹이를 위해 기다릴 줄 아는 자기 통제도 확인됐다.",
   facts=["🧠 아동용 마시멜로 테스트 유사 과제 통과 (Schnell et al. 2021)",
          "🧠 두족류는 뉴욕 선언(2024)의 의식 가능성 집단",
          "🎨 색맹이지만 피부로 색을 맞춘다"]),

 dict(id="squid", ko="유럽꼴뚜기", sci="Loligo vulgaris", emoji="🦑", group="두족류",
   evidence="ny", count=100_000_000_000, measured=False,
   countSrc="자릿수 추정 10¹¹ · Bar-On et al. PNAS 2018의 해양 무척추동물 자릿수 범위에서",
   blurb="빠르게 움직이며 무리로 사냥하고, 피부의 색 신호로 서로 소통한다. 두족류는 척추동물과 완전히 따로 진화한 계통에서 복잡한 신경계를 만들어냈다 — 지능이 지구에서 최소 두 번 발명됐다는 증거다.",
   facts=["🧠 척추동물과 독립적으로 진화한 복잡 신경계",
          "🧠 두족류는 뉴욕 선언(2024)의 의식 가능성 집단",
          "📊 전 세계 개체수는 자릿수 추정치"]),

 dict(id="honeybee", ko="서양꿀벌", sci="Apis mellifera", emoji="🐝", group="곤충",
   evidence="ny", count=2_542_827_900_000, measured=True,
   countSrc="FAOSTAT 2024 봉군 1억 171만 3,116개 × 봉군당 약 2만 5,000마리",
   blurb="뉴런이 100만 개도 안 되는데 0과 덧셈 개념을 배우고, 춤으로 꽃의 방향과 거리를 알려준다. 나쁜 경험을 하면 낙관적 판단이 줄어드는 '기분' 유사 상태도 측정됐다.",
   facts=["🧠 뉴런 약 96만 개 · 0 개념·기초 산수 학습 (Howard et al. 2018)",
          "🧠 곤충은 뉴욕 선언(2024)의 의식 가능성 집단",
          "🍯 봉군 1억 171만 개 × 약 2만 5,000마리"]),

 dict(id="bumblebee", ko="서양뒤영벌", sci="Bombus terrestris", emoji="🐝", group="곤충",
   evidence="ny", count=10_000_000_000, measured=False,
   countSrc="자릿수 추정 10¹⁰ · 야생 봉군 밀도 기반, 전 세계 총계 미출판",
   blurb="보상이 없어도 작은 나무공을 굴리며 논다 — 곤충의 '놀이'가 보고된 첫 사례다. 동료가 하는 걸 보고 새로운 문제 풀이법을 배우고, 그 방법이 무리에 퍼진다.",
   facts=["🧠 목적 없는 물체 놀이 관찰 (Galpayage Dona et al. 2022)",
          "🧠 사회적 학습으로 해법이 집단에 전파",
          "📊 전 세계 개체수는 자릿수 추정치"]),

 dict(id="crayfish", ko="가재류", sci="Astacidea", emoji="🦞", group="갑각류",
   evidence="ny", count=10_000_000_000, measured=False,
   countSrc="자릿수 추정 10¹⁰ · 전 세계 개체수 추정치 미출판",
   blurb="불안을 유발하는 상황에 놓으면 사람의 항불안제를 투여했을 때 행동이 정상으로 돌아온다. 통증 자극을 피하는 학습을 하고, 상처 부위를 집중적으로 문지른다. 십각류는 뉴욕 선언과 영국 법이 모두 감각 능력을 인정한 집단이다.",
   facts=["🧠 항불안제에 반응하는 불안 유사 상태 (Fossat et al. 2014)",
          "🧠 십각류는 뉴욕 선언(2024)의 의식 가능성 집단",
          "🇬🇧 영국 동물복지(감각)법 2022에서 감각 있는 존재로 인정"]),
]
